//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//

package uk.org.siri.siri;

import java.util.Date;

public class VehicleActivity {

	protected Date recordedAtTime;
		
	public Date getRecordedAtTime() {
		return recordedAtTime;
	}
	
	public void setRecordedAtTime(Date recordedAtTime) {
		this.recordedAtTime = recordedAtTime;
	}

}
